#!/usr/bin/env python3
"""
generate_juce_icons.py
======================
Reads Lucide SVG icon files and emits two C++ files:

  LucideIcons.h   – API declarations + inline helpers
  LucideIcons.cpp – icon data + function implementations

Usage
-----
  python3 tools/generate_juce_icons.py                         # all defaults
  python3 tools/generate_juce_icons.py --out-dir Source/GUI
  python3 tools/generate_juce_icons.py --filter wifi,user,settings

Runtime API (in your JUCE code)
--------------------------------
  // Draw centred in a bounds rectangle:
  LucideIcons::draw(g, "wifi", bounds);
  LucideIcons::draw(g, "wifi", bounds, juce::Colours::lightblue);
  LucideIcons::draw(g, "wifi", bounds, myColor, 0.5f);

  // Convenience – centred on a point at a given pixel size:
  LucideIcons::drawAt(g, "user", cx, cy, 20.0f, colour);

  // Create a Drawable you own (for caching / animation):
  auto d = LucideIcons::createDrawable("settings", colour);

  // Retrieve raw SVG string (currentColor preserved):
  juce::String svg = LucideIcons::getRawSvg("music");

  // Iterate available names:
  for (std::size_t i = 0; i < LucideIcons::ICON_COUNT; ++i)
      DBG(LucideIcons::NAMES[i]);
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


# ── SVG processing ─────────────────────────────────────────────────────────────

def minify_svg(content: str) -> str:
    """
    Collapse all whitespace runs to a single space and strip safe-to-remove
    inter-tag whitespace.  Preserves attribute values verbatim.
    """
    # Collapse newlines + leading indent inside tags
    content = re.sub(r'\s+', ' ', content.strip())
    # Remove whitespace between closing/opening tags
    content = re.sub(r'>\s+<', '><', content)
    return content


def safe_raw_delimiter(content: str, base: str = 'SVGICON') -> str:
    """
    Return a raw-string delimiter that does not appear in *content* as )DELIM".
    Appends a numeric suffix if necessary.
    """
    delim = base
    n = 0
    while f'){delim}"' in content:
        n += 1
        delim = f'{base}{n}'
    return delim


# ── Code generation ────────────────────────────────────────────────────────────

HEADER_TEMPLATE = """\
// ============================================================
// LucideIcons.h  —  AUTO-GENERATED, do not edit by hand.
// Generated by tools/generate_juce_icons.py
// Source:  lucide.dev  (ISC License)
// Icons:   {count} included
// ============================================================
#pragma once
#include <JuceHeader.h>
#include <memory>
#include <cstddef>

namespace LucideIcons {{

// ── Icon count ─────────────────────────────────────────────────────────────────
static constexpr std::size_t ICON_COUNT = {count};

// ── Sorted name list ───────────────────────────────────────────────────────────
/// All {count} available icon names, sorted alphabetically.
extern const char* const NAMES[ICON_COUNT];


// ── Core API ───────────────────────────────────────────────────────────────────

/// Draw a Lucide icon centred within `bounds`.
///
/// @param name     Icon name, e.g. "wifi", "user", "settings-2"
/// @param colour   Replaces `currentColor` in the SVG stroke/fill.
/// @param opacity  Opacity multiplier (0.0 – 1.0).
void draw(juce::Graphics&         g,
          juce::StringRef          name,
          juce::Rectangle<float>   bounds,
          juce::Colour             colour  = juce::Colours::white,
          float                    opacity = 1.0f);

/// Create a JUCE Drawable from the named icon (caller takes ownership).
/// Returns nullptr when the name is unknown.
std::unique_ptr<juce::Drawable>
createDrawable(juce::StringRef name,
               juce::Colour    colour = juce::Colours::white);

/// Return the raw SVG source string for `name` (with `currentColor` intact).
/// Returns an empty string when the name is unknown.
juce::String getRawSvg(juce::StringRef name);


// ── Convenience helpers ────────────────────────────────────────────────────────

/// Draw an icon centred on a pixel point at a fixed square size.
inline void drawAt(juce::Graphics& g,
                   juce::StringRef  name,
                   float            centreX,
                   float            centreY,
                   float            size,
                   juce::Colour     colour  = juce::Colours::white,
                   float            opacity = 1.0f)
{{
    draw(g, name,
         {{ centreX - size * 0.5f, centreY - size * 0.5f, size, size }},
         colour, opacity);
}}

/// Draw an icon into a square of `size` at the top-left corner `(x, y)`.
inline void drawAt(juce::Graphics& g,
                   juce::StringRef  name,
                   float            x,
                   float            y,
                   float            size,
                   juce::Colour     colour,
                   juce::RectanglePlacement placement,
                   float            opacity = 1.0f)
{{
    auto d = createDrawable(name, colour);
    if (d) d->drawWithin(g, {{ x, y, size, size }}, placement, opacity);
}}

}} // namespace LucideIcons
"""

CPP_HEADER = """\
// ============================================================
// LucideIcons.cpp  —  AUTO-GENERATED, do not edit by hand.
// Generated by tools/generate_juce_icons.py
// ============================================================
#include "LucideIcons.h"
#include <algorithm>
#include <cstring>

namespace LucideIcons {{

// ── Icon data ──────────────────────────────────────────────────────────────────

namespace {{

struct Entry {{ const char* name; const char* svg; }};

/// All icons, sorted alphabetically by name (required for binary search).
static const Entry DATA[] = {{
"""

CPP_FOOTER = """\
}};

static constexpr std::size_t DATA_SIZE = sizeof(DATA) / sizeof(DATA[0]);

}} // anonymous namespace


// ── Internal lookup ────────────────────────────────────────────────────────────

static juce::String colourToSvgHex(juce::Colour c)
{{
    return juce::String::formatted("#%02x%02x%02x",
                                   static_cast<int>(c.getRed()),
                                   static_cast<int>(c.getGreen()),
                                   static_cast<int>(c.getBlue()));
}}

static const Entry* findEntry(juce::StringRef name)
{{
    // Binary search on the sorted DATA array.
    const char* const cname = juce::String(name).toRawUTF8();
    int lo = 0, hi = static_cast<int>(DATA_SIZE) - 1;
    while (lo <= hi)
    {{
        const int mid = lo + (hi - lo) / 2;
        const int cmp = std::strcmp(DATA[mid].name, cname);
        if (cmp == 0) return &DATA[mid];
        if (cmp  < 0) lo = mid + 1;
        else          hi = mid - 1;
    }}
    return nullptr;
}}


// ── Public API ─────────────────────────────────────────────────────────────────

juce::String getRawSvg(juce::StringRef name)
{{
    const auto* e = findEntry(name);
    return e ? juce::String(e->svg) : juce::String{{}};
}}

std::unique_ptr<juce::Drawable>
createDrawable(juce::StringRef name, juce::Colour colour)
{{
    const auto* e = findEntry(name);
    if (!e) return nullptr;

    const juce::String colored =
        juce::String(e->svg).replace("currentColor", colourToSvgHex(colour));

    if (auto xml = juce::XmlDocument::parse(colored))
        return juce::Drawable::createFromSVG(*xml);

    return nullptr;
}}

void draw(juce::Graphics& g, juce::StringRef name,
          juce::Rectangle<float> bounds, juce::Colour colour, float opacity)
{{
    auto d = createDrawable(name, colour);
    if (d) d->drawWithin(g, bounds, juce::RectanglePlacement::centred, opacity);
}}


// ── Names array ────────────────────────────────────────────────────────────────

const char* const NAMES[ICON_COUNT] = {{
{names_list}
}};

}} // namespace LucideIcons
"""


def generate_header(icon_names: list[str], out_path: Path) -> None:
    content = HEADER_TEMPLATE.format(count=len(icon_names))
    out_path.write_text(content, encoding='utf-8')
    print(f'  {out_path.name:<30}  ({out_path.stat().st_size:,} bytes,  {len(icon_names)} icons)')


def generate_cpp(icon_data: list[tuple[str, str]], out_path: Path) -> None:
    lines: list[str] = [CPP_HEADER.format()]  # process {{ → { escaping

    for name, svg in icon_data:
        delim = safe_raw_delimiter(svg)
        lines.append(f'    {{ "{name}", R"{delim}({svg}){delim}" }},\n')

    names_list = '\n'.join(f'    "{name}",' for name, _ in icon_data)
    lines.append(CPP_FOOTER.format(names_list=names_list))

    content = ''.join(lines)
    out_path.write_text(content, encoding='utf-8')
    kb = out_path.stat().st_size // 1024
    print(f'  {out_path.name:<30}  ({kb:,} KB,  {len(icon_data)} icons)')


# ── Main ───────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description='Generate JUCE C++ icon wrapper from Lucide SVG icons.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        'icons_dir',
        nargs='?',
        default='/home/jjh/Documents/Repositorys/SlopAudio-Connect/Assets/lucide-main/icons',
        help='Directory containing *.svg files (default: Lucide assets path)',
    )
    p.add_argument(
        '--out-dir', '-o',
        default='/home/jjh/Documents/Repositorys/SlopAudio-Connect/Source/GUI',
        help='Output directory for LucideIcons.h and LucideIcons.cpp',
    )
    p.add_argument(
        '--filter', '-f',
        default=None,
        metavar='NAME,NAME,...',
        help='Comma-separated list of icon names to include (default: all)',
    )
    p.add_argument(
        '--prefix',
        default='Lucide',
        help='Class/namespace prefix for generated files (default: Lucide → LucideIcons)',
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    icons_dir = Path(args.icons_dir)
    out_dir   = Path(args.out_dir)

    if not icons_dir.is_dir():
        print(f'ERROR: icons directory not found: {icons_dir}', file=sys.stderr)
        sys.exit(1)

    out_dir.mkdir(parents=True, exist_ok=True)

    # ── Filter ────────────────────────────────────────────────────────────────
    name_filter: set[str] | None = None
    if args.filter:
        name_filter = {n.strip() for n in args.filter.split(',')}
        print(f'Filter: {len(name_filter)} icon(s) requested')

    # ── Collect ───────────────────────────────────────────────────────────────
    print(f'Scanning  {icons_dir} ...')
    svg_files = sorted(icons_dir.glob('*.svg'))

    if not svg_files:
        print('ERROR: no .svg files found in icons_dir.', file=sys.stderr)
        sys.exit(1)

    icon_data: list[tuple[str, str]] = []
    skipped   = 0
    not_found: list[str] = []

    for svg_path in svg_files:
        name = svg_path.stem  # filename without .svg

        if name_filter is not None and name not in name_filter:
            continue

        try:
            raw = svg_path.read_text(encoding='utf-8')
        except OSError as exc:
            print(f'  WARNING: cannot read {svg_path.name}: {exc}')
            skipped += 1
            continue

        icon_data.append((name, minify_svg(raw)))

    # Report any requested-but-missing icons
    if name_filter is not None:
        found_names = {n for n, _ in icon_data}
        not_found   = sorted(name_filter - found_names)
        if not_found:
            print(f'  WARNING: {len(not_found)} requested icon(s) not found: '
                  + ', '.join(not_found))

    # Ensure sorted for binary search in generated code
    icon_data.sort(key=lambda x: x[0])

    total = len(icon_data)
    print(f'  {total} icons collected'
          + (f'  ({skipped} skipped)' if skipped else ''))

    if total == 0:
        print('ERROR: nothing to generate.', file=sys.stderr)
        sys.exit(1)

    # ── Generate ──────────────────────────────────────────────────────────────
    print(f'\nWriting to  {out_dir} ...')
    generate_header([n for n, _ in icon_data], out_dir / 'LucideIcons.h')
    generate_cpp(icon_data,                    out_dir / 'LucideIcons.cpp')
    print('\nDone.')


if __name__ == '__main__':
    main()
